export const teknisiDetailData: { [key: string]: any } = {
  '1': {
    id: '1',
    name: 'Budi Santoso',
    location: 'Solo',
    rating: 4.9,
    reviews: 124,
    specialties: ['Laptop', 'PC', 'Software'],
    experience: '8 tahun',
    verified: true,
    responseTime: '< 1 jam',
    completedJobs: 450,
    photo: 'https://images.unsplash.com/photo-1624640010799-7cdb3b4b1ae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNjczMzM4OTQ1fDA&ixlib=rb-4.1.0&q=80&w=400',
    description:
      'Teknisi berpengalaman dengan spesialisasi perbaikan laptop dan PC. Sudah menangani berbagai macam brand seperti Asus, Lenovo, HP, Dell, dan Acer. Ahli dalam troubleshooting hardware dan software.',
    skills: [
      { name: 'Perbaikan Hardware', level: 95 },
      { name: 'Install Software', level: 98 },
      { name: 'Troubleshooting', level: 92 },
      { name: 'Data Recovery', level: 85 },
    ],
    services: [
      { name: 'Service Laptop', duration: '2-4 jam' },
      { name: 'Install Windows', duration: '1-2 jam' },
      { name: 'Upgrade RAM/SSD', duration: '30 menit' },
      { name: 'Cleaning Laptop', duration: '1 jam' },
      { name: 'Ganti LCD/Keyboard', duration: '1-2 jam' },
    ],
    recentReviews: [
      {
        id: '1',
        user: 'Rina Wijaya',
        rating: 5,
        date: '28 Nov 2025',
        comment: 'Sangat profesional dan cepat! Laptop saya yang lemot jadi kencang lagi. Recommended!',
      },
      {
        id: '2',
        user: 'Agus Prasetyo',
        rating: 5,
        date: '25 Nov 2025',
        comment: 'Pelayanan memuaskan, harga terjangkau. Teknisinya ramah dan menjelaskan dengan detail.',
      },
      {
        id: '3',
        user: 'Siti Nurhaliza',
        rating: 4,
        date: '20 Nov 2025',
        comment: 'Bagus, tapi agak lama menunggu spare part. Overall puas dengan hasilnya.',
      },
    ],
    availability: {
      senin: '08:00 - 20:00',
      selasa: '08:00 - 20:00',
      rabu: '08:00 - 20:00',
      kamis: '08:00 - 20:00',
      jumat: '08:00 - 20:00',
      sabtu: '09:00 - 17:00',
      minggu: 'Libur',
    },
  },
  '2': {
    id: '2',
    name: 'Ahmad Hidayat',
    location: 'Karanganyar',
    rating: 4.8,
    reviews: 98,
    specialties: ['Jaringan', 'CCTV', 'WiFi'],
    experience: '6 tahun',
    verified: true,
    responseTime: '< 2 jam',
    completedJobs: 320,
    photo: 'https://images.unsplash.com/photo-1752856408620-2e6fc6ac072f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBJVCUyMHdvcmtlciUyMHBvcnRyYWl0fGVufDF8fHx8MTc2NzMzODk0NXww&ixlib=rb-4.1.0&q=80&w=400',
    description:
      'Spesialis instalasi dan maintenance jaringan komputer, CCTV, dan WiFi. Berpengalaman menangani proyek untuk rumah, kantor, dan toko. Ahli dalam konfigurasi router, troubleshooting koneksi, dan optimasi jaringan.',
    skills: [
      { name: 'Instalasi Jaringan', level: 92 },
      { name: 'Konfigurasi Router', level: 90 },
      { name: 'CCTV Setup', level: 95 },
      { name: 'Troubleshooting WiFi', level: 88 },
    ],
    services: [
      { name: 'Instalasi CCTV', duration: '3-5 jam' },
      { name: 'Setup WiFi Router', duration: '1-2 jam' },
      { name: 'Konfigurasi Jaringan', duration: '2-3 jam' },
      { name: 'Maintenance CCTV', duration: '1-2 jam' },
      { name: 'Troubleshooting Koneksi', duration: '1 jam' },
    ],
    recentReviews: [
      {
        id: '1',
        user: 'Budi Hermawan',
        rating: 5,
        date: '30 Nov 2025',
        comment: 'Instalasi CCTV rumah saya sangat rapi dan profesional. Hasil gambarnya jernih!',
      },
      {
        id: '2',
        user: 'Yuni Astuti',
        rating: 5,
        date: '26 Nov 2025',
        comment: 'WiFi di rumah jadi kencang dan stabil setelah dikonfigurasi mas Ahmad. Makasih!',
      },
      {
        id: '3',
        user: 'Dedi Wijaya',
        rating: 4,
        date: '22 Nov 2025',
        comment: 'Pekerjaan bagus, hanya perlu sedikit lebih cepat. Tapi hasilnya memuaskan.',
      },
    ],
    availability: {
      senin: '09:00 - 18:00',
      selasa: '09:00 - 18:00',
      rabu: '09:00 - 18:00',
      kamis: '09:00 - 18:00',
      jumat: '09:00 - 18:00',
      sabtu: '10:00 - 16:00',
      minggu: 'Libur',
    },
  },
  '3': {
    id: '3',
    name: 'Dewi Lestari',
    location: 'Sukoharjo',
    rating: 5.0,
    reviews: 156,
    specialties: ['HP', 'Tablet', 'Layar'],
    experience: '10 tahun',
    verified: true,
    responseTime: '< 30 menit',
    completedJobs: 580,
    photo: 'https://images.unsplash.com/photo-1712174766230-cb7304feaafe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwd29tYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDV8MA&ixlib=rb-4.1.0&q=80&w=400',
    description:
      'Teknisi handphone dan tablet berpengalaman dengan keahlian khusus dalam perbaikan layar, ganti baterai, dan software. Menangani semua brand: Samsung, Oppo, Vivo, Xiaomi, iPhone, dan lainnya. Garansi untuk setiap perbaikan.',
    skills: [
      { name: 'Ganti Layar HP', level: 98 },
      { name: 'Perbaikan IC', level: 90 },
      { name: 'Software HP', level: 95 },
      { name: 'Ganti Baterai', level: 97 },
    ],
    services: [
      { name: 'Ganti Layar LCD', duration: '30-60 menit' },
      { name: 'Ganti Baterai', duration: '20-30 menit' },
      { name: 'Flash/Install Ulang', duration: '1-2 jam' },
      { name: 'Service Mati Total', duration: '2-4 jam' },
      { name: 'Ganti Kamera/Speaker', duration: '30-60 menit' },
    ],
    recentReviews: [
      {
        id: '1',
        user: 'Andi Kurniawan',
        rating: 5,
        date: '1 Des 2025',
        comment: 'Layar HP saya diganti dengan cepat dan hasilnya sempurna. Sangat recommended!',
      },
      {
        id: '2',
        user: 'Maya Sari',
        rating: 5,
        date: '29 Nov 2025',
        comment: 'Mbak Dewi ramah dan profesional. HP saya yang bootloop berhasil diselamatkan!',
      },
      {
        id: '3',
        user: 'Rizki Pratama',
        rating: 5,
        date: '27 Nov 2025',
        comment: 'Fast response, harga terjangkau, hasil memuaskan. The best!',
      },
    ],
    availability: {
      senin: '08:00 - 20:00',
      selasa: '08:00 - 20:00',
      rabu: '08:00 - 20:00',
      kamis: '08:00 - 20:00',
      jumat: '08:00 - 20:00',
      sabtu: '08:00 - 18:00',
      minggu: '10:00 - 16:00',
    },
  },
};
