export const teknisiList = [
  {
    id: '1',
    name: 'Budi Santoso',
    location: 'Solo',
    rating: 4.9,
    specialties: ['Laptop', 'PC', 'Software'],
    experience: '8 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'BS',
    photo: 'https://images.unsplash.com/photo-1624640010799-7cdb3b4b1ae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNjczMzM4OTQ1fDA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '2',
    name: 'Ahmad Hidayat',
    location: 'Karanganyar',
    rating: 4.8,
    specialties: ['Jaringan', 'CCTV', 'WiFi'],
    experience: '6 tahun',
    verified: true,
    responseTime: '< 2 jam',
    avatar: 'AH',
    photo: 'https://images.unsplash.com/photo-1752856408620-2e6fc6ac072f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBJVCUyMHdvcmtlciUyMHBvcnRyYWl0fGVufDF8fHx8MTc2NzMzODk0NXww&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '3',
    name: 'Dewi Lestari',
    location: 'Sukoharjo',
    rating: 5.0,
    specialties: ['HP', 'Tablet', 'Layar'],
    experience: '10 tahun',
    verified: true,
    responseTime: '< 30 menit',
    avatar: 'DL',
    photo: 'https://images.unsplash.com/photo-1712174766230-cb7304feaafe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwd29tYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDV8MA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '4',
    name: 'Eko Prasetyo',
    location: 'Solo',
    rating: 4.7,
    specialties: ['Printer', 'Scanner', 'Hardware'],
    experience: '5 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'EP',
    photo: 'https://images.unsplash.com/photo-1747811854382-11025aa5180b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBlbmdpbmVlciUyMHBvcnRyYWl0fGVufDF8fHx8MTc2NzMyNDE3MHww&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '5',
    name: 'Siti Rahayu',
    location: 'Klaten',
    rating: 4.9,
    specialties: ['MacBook', 'iMac', 'iOS'],
    experience: '7 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'SR',
    photo: 'https://images.unsplash.com/photo-1605504836193-e77d3d9ede8a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHRlY2huaWNpYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDZ8MA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '6',
    name: 'Rudi Hartono',
    location: 'Sragen',
    rating: 4.6,
    specialties: ['Gaming PC', 'VGA', 'PSU'],
    experience: '4 tahun',
    verified: true,
    responseTime: '< 3 jam',
    avatar: 'RH',
    photo: 'https://images.unsplash.com/photo-1674471361339-2e1e1dbd3e73?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBjb21wdXRlciUyMHRlY2huaWNpYW58ZW58MXx8fHwxNzY3MzM4OTQ2fDA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '7',
    name: 'Lina Marlina',
    location: 'Solo',
    rating: 4.8,
    specialties: ['Data Recovery', 'HDD/SSD', 'Backup'],
    experience: '9 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'LM',
    photo: 'https://images.unsplash.com/photo-1712174766230-cb7304feaafe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwd29tYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDV8MA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '8',
    name: 'Bambang Wijaya',
    location: 'Karanganyar',
    rating: 4.5,
    specialties: ['Server', 'NAS', 'Linux'],
    experience: '12 tahun',
    verified: true,
    responseTime: '< 2 jam',
    avatar: 'BW',
    photo: 'https://images.unsplash.com/photo-1624640010799-7cdb3b4b1ae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNjczMzM4OTQ1fDA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '9',
    name: 'Fitri Handayani',
    location: 'Sukoharjo',
    rating: 4.9,
    specialties: ['Laptop Gaming', 'Cooling System', 'Overclocking'],
    experience: '6 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'FH',
    photo: 'https://images.unsplash.com/photo-1605504836193-e77d3d9ede8a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHRlY2huaWNpYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDZ8MA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '10',
    name: 'Joko Susilo',
    location: 'Klaten',
    rating: 4.7,
    specialties: ['Monitor', 'Proyektor', 'Display'],
    experience: '5 tahun',
    verified: true,
    responseTime: '< 2 jam',
    avatar: 'JS',
    photo: 'https://images.unsplash.com/photo-1752856408620-2e6fc6ac072f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBJVCUyMHdvcmtlciUyMHBvcnRyYWl0fGVufDF8fHx8MTc2NzMzODk0NXww&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '11',
    name: 'Nia Kurniasih',
    location: 'Solo',
    rating: 5.0,
    specialties: ['Smartwatch', 'Wearables', 'IoT'],
    experience: '4 tahun',
    verified: true,
    responseTime: '< 1 jam',
    avatar: 'NK',
    photo: 'https://images.unsplash.com/photo-1712174766230-cb7304feaafe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB0ZWNobmljaWFuJTIwd29tYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjczMzg5NDV8MA&ixlib=rb-4.1.0&q=80&w=400',
  },
  {
    id: '12',
    name: 'Hendra Gunawan',
    location: 'Sragen',
    rating: 4.8,
    specialties: ['Audio System', 'Speaker', 'Microphone'],
    experience: '8 tahun',
    verified: true,
    responseTime: '< 2 jam',
    avatar: 'HG',
    photo: 'https://images.unsplash.com/photo-1674471361339-2e1e1dbd3e73?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBjb21wdXRlciUyMHRlY2huaWNpYW58ZW58MXx8fHwxNzY3MzM4OTQ2fDA&ixlib=rb-4.1.0&q=80&w=400',
  },
];

// Helper function to get teknisi ID by name
export const getTeknisiIdByName = (name: string): string | null => {
  const teknisi = teknisiList.find(t => t.name === name);
  return teknisi ? teknisi.id : null;
};